server:
  port: 8082

spring:
  datasource:
    # 连接数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: 略
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis-plus:
  #  configuration:
  #    # 打印日志, 方便看SQL
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键自增
      id-type: auto

oss:
  bucket: 略
  domain: 略
  access-key: 略
  secret-key: 略
  in-date-path: false
